UI/Controllers/AUDescriptionController.cs
using AutoMapper;
using BL.IServices;
using DTOs;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;
using UI.Extensions;
using UI.Models;

namespace UI.Controllers
{
    [Authorize]
    public class AUDescriptionController : Controller
    {
        private readonly IAUDescriptionManager _auManager;
        private readonly IAboutUsManager _aboutUsManager;
        private readonly IValidator<AUDescriptionCreateDto> _auCreateDtoValidator;
        private readonly IValidator<AboutUsDescriptionViewModel> _auvmCreateDtoValidator;
        private readonly IMapper _mapper;

        public AUDescriptionController(IAUDescriptionManager auManager, IValidator<AUDescriptionCreateDto> auCreateDtoValidator, IMapper mapper, IAboutUsManager aboutUsManager, IValidator<AboutUsDescriptionViewModel> auvmCreateDtoValidator)
        {
            _auManager = auManager;
            _auCreateDtoValidator = auCreateDtoValidator;
            _mapper = mapper;
            _aboutUsManager = aboutUsManager;
            _auvmCreateDtoValidator = auvmCreateDtoValidator;
        }

        public async Task<IActionResult> Index()
        {
            var response = await _auManager.GetAllAsync();
            return this.ResponseView(response);
        }

        public async Task<IActionResult> Create()
        {
            var response = await _aboutUsManager.GetActiveAsync();
            var model = new AboutUsDescriptionViewModel
            {
                Abouts = new SelectList(response.Data, "Id", "Title")
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AboutUsDescriptionViewModel model)
        {
            var result = _auvmCreateDtoValidator.Validate(model);
            if (result.IsValid)
            {
                var dto = _mapper.Map<AUDescriptionCreateDto>(model);
                var createResponse = await _auManager.CreateAsync(dto);
                return this.ResponseRedirectAction(createResponse, "Index");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
            }
            var response = await _aboutUsManager.GetAllAsync();
            model.Abouts = new SelectList(response.Data, "Id", "Description", model.AboutUsId);
            return View(model);
        }

        public async Task<IActionResult> Update(int id)
        {
            var response = await _auManager.GetByIdAsync<AUDescriptionUpdateDto>(id);
            var droplistResp = await _aboutUsManager.GetActiveAsync();
            ViewBag.mydroplist = new SelectList(droplistResp.Data, "Id", "Title");
            return View(response.Data);
        }

        [HttpPost]
        public async Task<IActionResult> Update(AUDescriptionUpdateDto dto)
        {
            var response = await _auManager.UpdateAsync(dto);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Remove(int id)
        {
            var response = await _auManager.RemoveAsync(id);
            return this.ResponseRedirectAction(response, "Index");
        }
    }
}

UI/Controllers/CustomerController.cs
using AutoMapper;
using BL.IServices;
using DTOs;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using UI.Extensions;

namespace UI.Controllers
{
    public class CustomerController : Controller
	{
		private readonly ICustomerManager _customerManager;
		private readonly IValidator<CustomerCreateDto> _customerCreateDtoValidator;
		private readonly IMapper _mapper;

		public CustomerController(ICustomerManager customerManager, IValidator<CustomerCreateDto> customerCreateDtoValidator, IMapper mapper)
		{
			_customerManager = customerManager;
			_customerCreateDtoValidator = customerCreateDtoValidator;
			_mapper = mapper;
		}
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var response = await _customerManager.GetAllAsync();
            return this.ResponseView(response);
        }
        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var response = await _customerManager.GetByIdAsync<CustomerListDto>(id);
            return View(response.Data);
        }

        public IActionResult Create()
        {
            var model = new CustomerCreateDto();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CustomerCreateDto model)
        {
            var result = _customerCreateDtoValidator.Validate(model);
            if (result.IsValid)
            {
                var dto = _mapper.Map<CustomerCreateDto>(model);
                var createResponse = await _customerManager.CreateAsync(dto);
                return this.ResponseRedirectActionWithController(createResponse, "Index","Home");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
            }
            return View(model);
        }
        [Authorize]
        public async Task<IActionResult> Update(int id)
        {
            var response = await _customerManager.GetByIdAsync<CustomerUpdateDto>(id);
            return View(response.Data);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Update(CustomerUpdateDto dto)
        {
            var response = await _customerManager.UpdateAsync(dto);
            return RedirectToAction("Index");
        }
        [Authorize]
        public async Task<IActionResult> Remove(int id)
        {
            var response = await _customerManager.RemoveAsync(id);
            return this.ResponseRedirectAction(response, "Index");
        }
    }
}

UI/Views/Customer/Create.cshtml
@model CustomerCreateDto
@{
	ViewData["Title"] = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="service-two">
	<img src="assets/images/shapes/service-shape-1-3.png" class="service-two__shape-1 float-bob-y" alt="">
	<div class="container">
		<div class="row">
			<div class="col-xl-5 d-flex">
				<div class="my-auto">
					<div class="service-two__moc-box wow fadeInUp" data-wow-duration="1500ms">
						<img src="~/seclight/assets/images/resources/service-moc-11-1.png" class="float-bob-x" alt="">
					</div><!-- /.service-two__moc-box -->
				</div><!-- /.my-auto -->
			</div><!-- /.col-lg-5 -->
			<div class="col-xl-7">
				<div class="service-two__content">
					<div class="block-title block-title__two text-center" style="height:300px;display:flex;align-items:center">
						<h1 style="color:white"><b>Müşteri Hizmet Destek Formu</b></h1>
					</div><!-- /.block-title text-center -->
				</div><!-- /.service-two__content -->
			</div><!-- /.col-lg-7 -->
		</div><!-- /.row -->
	</div><!-- /.container -->
</section><!-- /.service-two -->

<section class="service-three" style="height:250px !important;">
	<div class="container">
		<div class="block-title block-title__two text-center">
			<h4>Müşteri Destek Formu</h4>
			<h3>Profesyonel, Optimize ve Hızlı</h3>
		</div><!-- /.block-title text-center -->
	</div><!-- /.container -->
</section><!-- /.service-three -->

<section class="contact-two">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 d-flex">
				<div class="my-auto">
					<div class="contact-two__content">
						<div class="block-title block-title__two text-left">
						</div><!-- /.block-title text-center -->
					</div><!-- /.contact-two__content -->
				</div><!-- /.my-auto -->
			</div><!-- /.col-lg-6 -->
			<div class="col-lg-8">
				<form asp-action="Create" method="post" class="contact-form-validated contact-two__form">
					<div asp-validation-summary="ModelOnly" class="text-color"></div>
					<img src="~/seclight/assets/images/shapes/contact-shape-2.png" class="contact-two__form-shape" alt="">
					<div class="contact-two__form-inner wow fadeInRight" data-wow-duration="1500ms">
						<div class="row">
							<div class="col-md-6">
								<input asp-for="CustomerName" type="text" placeholder="Adınız *" name="CustomerName">
								<span asp-validation-for="CustomerName"></span>
							</div><!-- /.col-md-6 -->
							<div class="col-md-6">
								<input asp-for="CustomerSurName" type="text" placeholder="Soyadınız *" name="CustomerSurName">
								<span asp-validation-for="CustomerSurName"></span>
							</div><!-- /.col-md-6 -->
							<div class="col-md-12">
								<input asp-for="CustomerMail" type="email" placeholder="Email Adresiniz *" name="CustomerMail">
								<span asp-validation-for="CustomerMail"></span>
							</div><!-- /.col-md-12 -->
							<div class="col-md-12">
								<input asp-for="CustomerPhone" type="tel" placeholder="Telefon Numaranız *" name="CustomerPhone">
								<span asp-validation-for="CustomerPhone"></span>
							</div><!-- /.col-md-12 -->
							<div class="col-md-12">
								<select asp-for="ProductType" name="ProductType" class="selectpicker">
									<option value="Mobil Uygulama Geliştirme">Mobil Uygulama Geliştirme</option>
									<option value="Web Geliştirme">Web Geliştirme</option>
									<option value="Masaüstü Yazılımı Geliştirme">Masaüstü Yazılımı Geliştirme</option>
									<option value="Logo Tasarımı">Logo Tasarımı</option>
									<option value="Yazılım Danışmanlığı">Yazılım Danışmanlığı</option>
								</select>
								<span asp-validation-for="ProductType"></span>
							</div><!-- /.col-md-12 -->
							<div class="col-md-12">
								<textarea asp-for="Description" name="Description" placeholder="Lütfen almak istediğiniz destek ile ilgili ayrıntılı bilgi veriniz."></textarea>
								<span asp-validation-for="Description"></span>
							</div><!-- /.col-md-6 -->
							<div class="col-md-12" style="visibility:hidden">
								<input asp-for="Status" type="checkbox" placeholder="Aktiflik *" checked name="Status">
								<span asp-validation-for="Status"></span>
							</div><!-- /.col-md-12 -->
							<div class="col-md-12">
								<button type="submit" class="thm-btn contact-two__btn">Gönder</button>
								<!-- /.thm-btn contact-two__btn -->
							</div><!-- /.col-md-12 -->
						</div><!-- /.row -->
					</div><!-- /.contact-two__form-inner -->
				</form><!-- /.contact-two__form -->
			</div><!-- /.col-lg-6 -->
		</div><!-- /.row -->
	</div><!-- /.container -->
</section><!-- /.contact-two -->
<br /><br /><br />

UI/Views/Customer/Index.cshtml
@model List<CustomerListDto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutPanel.cshtml";
}

<div class="row">
	<div class="col-lg-12">
		<div class="statbox widget box box-shadow">
			<div class=" align-left">
				<div class="row">
					<div class="col-md-12 mb-2">
						<button onclick="CreateData()" class="btn-creative btn-3 btn-3e flaticon-plus-1"><span>Müşteri Hizmet Formu</span></button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row layout-spacing">
	<div class="col-lg-12">
		<div class="statbox widget box box-shadow">
			<div class="widget-content widget-content-area">
				<div class="table-responsive mb-4">
					<table id="column-filter" class="table table-bordered table-hover">
						<thead>
							<tr>
								<th hidden class="checkbox-column"> Record No. </th>
								<th>Başlık</th>
								<th>Kayıt Tarihi</th>
								<th>Aktiflik</th>
								<th class="text-center">İşlemler</th>
							</tr>
						</thead>
						<tbody>
							@foreach (var item in Model)
							{
								<tr>
									<td hidden class="checkbox-column"> 1 </td>
									<td>@item.CustomerName</td>
									<td>@item.CustomerSurName</td>
									<td>@item.CustomerMail</td>
									<td>@item.CreatedDate</td>
									@if (@item.Status == true)
									{
										<td><span class="shadow-none badge badge-success">Aktif</span></td>
									}
									else
									{
										<td><span class="shadow-none badge badge-danger">Aktif Değil</span></td>
									}
									<td class="text-center">
										<ul class="table-controls">
											<li><a asp-controller="AUDescription" asp-action="Create" asp-route-id="@item.Id" data-toggle="tooltip" data-placement="top" title="İçerik Ekle"><i class="flaticon-plus-1  bg-primary p-1 text-white br-6 mb-1"></i></a> </li>
											<li><a asp-action="Details" asp-route-id="@item.Id" data-toggle="tooltip" data-placement="top" title="Görüntüle"><i class="flaticon-scale  bg-primary p-1 text-white br-6 mb-1"></i></a> </li>
											<li><a asp-action="Update" asp-route-id="@item.Id" data-toggle="tooltip" data-placement="top" title="Güncelle"><i class="flaticon-edit  bg-warning p-1 text-white br-6 mb-1"></i></a></li>
											<li><a asp-action="Remove" asp-route-id="@item.Id" data-toggle="tooltip" data-placement="top" title="Sil"><i class="flaticon-delete  bg-danger p-1 text-white br-6 mb-1"></i></a></li>
										</ul>
									</td>
								</tr>
							}

						</tbody>
						<tfoot>
							<tr>
								<th hidden class="checkbox-column"></th>
								<th>Başlık</th>
								<th>Kayıt Tarihi</th>
								<th>Aktiflik</th>
								<th class="text-center">İşlemler</th>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>